// FILE: src/theme/brand.ts
// Single source of truth for brand + UI copy. All shipped strings live here.

const BRAND = {
  appName: 'JobMesh',
  tagline: 'Tech jobs in India — without the fluff',
  fullName: 'JobMesh',
  description: 'Fresh tech jobs from top Indian companies, updated daily. Direct apply links, no middlemen.',
  twitter: '',
  contact: '/legal',
} as const;

const BRAND_SPLIT = { first: 'Job', accent: 'Mesh' } as const;

const SKETCH_FONT = "'Source Serif 4', 'Iowan Old Style', Georgia, ui-serif, serif";

const PALETTE = {
  primary: '#2D6A4F',
  primarySoft: 'rgba(45,106,79,0.10)',
  success: '#0F7B5A',
  danger: '#C5380F',
  warning: '#B66B0A',
  info: '#0A6CC7',
} as const;

const COPY = {
  nav: {
    today: 'Today',
    companies: 'Companies',
    browseJobs: 'Jobs',
    myProgress: 'Progress',
    hiring: 'Hiring',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
  },
  home: {
    heroLabel: 'Tech jobs in India — without the fluff',
    heroTitle1: 'Find your next',
    heroTitle2: 'tech role in India',
    heroSubtitle: 'Fresh roles from top Indian tech companies, updated daily. Direct apply links, no middlemen.',
    heroCTA: 'Browse jobs',
    heroSecondaryCTA: 'View companies',
    stat1Value: '50+',
    stat1Label: 'Companies',
    stat2Value: 'Daily',
    stat2Label: 'Fresh updates',
    companiesSectionLabel: 'Hiring now',
    companiesSectionTitle1: 'Top companies in',
    companiesSectionTitle2: 'India',
    scrollLeft: 'Scroll left',
    scrollRight: 'Scroll right',
    fullDirectory: 'Full directory',
    jobsSectionLabel: 'Fresh picks',
    jobsSectionTitle: 'Latest opportunities',
    viewAll: 'View all',
    loadMore: 'Load more',

    // ── Guest landing page ──────────────────────────────────────────
    // Section 1 — ticker. `newRolesToday` is used when at least one role landed
    // in the last 24h; `rolesAddedDaily` is the evergreen zero-state fallback.
    newRolesToday: 'new roles added today',
    tickerDaily: 'Roles added daily',
    tickerHiring: 'are hiring',
    tickerActivePrefix: 'active positions across',
    tickerCompaniesSuffix: 'companies',
    tickerSuffix: 'No account needed to apply',

    // Section 2 — hero
    rolesAddedToday: 'roles added today',
    rolesAddedDaily: 'New roles daily',
    heroHeadPrefix: 'Find your next',
    heroHeadAccent: 'tech role',
    heroHeadSuffix: 'in India',
    heroSubtitleBase:
      'Fresh roles from top Indian tech companies, updated daily. Direct apply links, no middlemen',
    noAccountRequired: 'no account required',
    searchPlaceholder: 'Job title, skill, or company…',
    searchAriaLabel: 'Search tech jobs',
    searchButton: 'Search',
    locationDefault: 'All India',
    locationAriaLabel: 'Change location — currently all of India',
    quickFiltersLabel: 'Try',
    quickFilters: ['React', 'Python', 'Data analyst', 'Remote', 'Fresher / Entry', 'DevOps', 'Backend'],

    // Section 3 — trust metrics
    trustHeading: 'JobMesh at a glance',
    metricRolesLabel: 'Active roles',
    metricCompaniesLabel: 'Companies',
    metricFreshValue: 'Daily',
    metricFreshLabel: 'Fresh updates',
    metricDirectValue: 'Direct',
    metricDirectLabel: 'Apply links',

    // Section 4 — logo strip
    logoStripLabel: 'Trusted by teams at',

    // Section 5 — how it works
    howItWorksLabel: 'How it works',
    step1Title: 'Browse or search',
    step1Desc: 'Filter by skill, location, experience, or company. No signup wall.',
    step2Title: 'Read the details',
    step2Desc: 'Full job description, salary when listed, workplace type and department.',
    step3Title: 'Apply directly',
    step3Desc: "Every link goes to the company's career page. No middlemen, ever.",

    // Sections 6 + 7 — headings and the feed's trailing CTA
    companiesHeading: 'Top companies',
    jobsHeading: 'Latest opportunities',
    openRole: 'open role',
    openRoles: 'open roles',
    browseAllPrefix: 'Browse all',
    browseAllSuffix: 'roles',

    // Section 8 — employer cross-sell
    employerCTATitle: 'Hiring for your team?',
    employerCTASubtitle: 'Post jobs, manage applicants, and schedule interviews — free.',
    employerCTAButton: 'Employer portal',
  },
  jobs: {
    pageLabel: 'Opportunities',
    pageTitle: 'All tech jobs',
    rolesAvailable: 'roles available',
    noJobsTitle: 'No jobs found',
    noJobsBody: 'Try a different company or view all roles.',
    noEntryJobsBody: 'No entry-level roles found. Try turning off the fresher filter.',
    clearFilters: 'Clear filters',
    allJobs: 'All jobs',
    allCompanies: 'All companies',
    experienceLabel: 'Experience',
    companiesLabel: 'Companies',
    entryLevel: 'Entry level / Fresher',
    allLevels: 'All experience levels',
    applyNow: 'Apply now',
    readMore: 'Read more',
    showLess: 'Show less',
    postedPrefix: 'Posted',
    postedNA: 'No date',
    feedTitle: 'Job feed',
    rolesLabel: 'roles',
    filterLabel: 'Filter',
  },
  progress: {
    pageLabel: 'Tracking',
    pageTitle: 'My progress',
    backToJobs: 'Back to jobs',
    todayLabel: 'Today',
    noStreak: 'No streak yet',
    historyLabel: 'Recent applications',
    historySubtitle: 'Your latest applied jobs, useful for follow-ups and interview prep.',
    emptyTitle: 'No applications tracked yet',
    emptyBody: 'Start applying from the jobs feed and your recent history will appear here.',
  },
  directory: {
    pageLabel: 'Company directory',
    pageTitle1: 'Tech companies',
    pageTitle2: 'hiring in India',
    subtitle: 'Companies actively hiring across India — updated daily.',
    searchPlaceholder: 'Search companies…',
    searchAriaLabel: 'Search companies',
    sortAriaLabel: 'Sort companies',
    noCompaniesTitle: 'No companies found',
    noCompaniesBody: 'Try a different search term or clear your filters.',
    sortAZ: 'A → Z',
    sortZA: 'Z → A',
    sortMostHiring: 'Most hiring',
    documentTitle: 'Tech companies hiring in India · JobMesh',
  },
  footer: {
    navigateTitle: 'Navigate',
    jobFeedLink: 'Job feed',
    companiesLink: 'Companies',
    legalTitle: 'Legal',
    legalInfoLink: 'Legal info',
    privacyLink: 'Privacy',
    contactLink: 'Contact',
    disclaimer: 'A non-commercial aggregator. Job details are collected automatically — verify directly with employers.',
  },
  legal: {
    pageLabel: 'Legal',
    pageTitle: 'Legal information',
    lastUpdated: 'Last updated: March 2026',
    contactTitle: 'Contact',
    contactBody: 'For questions, data deletion requests, or legal enquiries, reach out at layer3studios.team@gmail.com.',
    sections: [],
  },
  site: {
    documentTitleJobs: 'Browse tech jobs in India · JobMesh',
    documentTitleProgress: 'My progress · JobMesh',
  },
  trends: {
    pageLabel: 'Market signal',
    pageTitle: 'Hiring trends in',
    pageTitleAccent: 'India',
    subtitle: 'How tech hiring is moving — posting momentum, role demand, and who is ramping up.',
    shareButtonLabel: 'Share',
    shareTitle: 'Hiring trends in India · JobMesh',
    documentTitle: 'Hiring trends in India · JobMesh',
    errorTitle: "Couldn't load trends",
    errorBody: 'Something went wrong. Try refreshing.',
    emptyTitle: 'Not enough data yet',
    emptyBody: 'Trend signals will appear here as more roles come in.',
    updatedPrefix: 'Updated',
    summaryTotalRoles: 'Open roles',
    summaryNewThisWeek: 'New this week',
    summaryMomentum: 'Week over week',
    summaryCompanies: 'Companies tracked',
    momentumTitle: 'Posting momentum',
    momentumSub: 'New roles added per day over the last 60 days',
    categoriesTitle: 'Role demand',
    categoriesSub: 'Share of open roles by category, with week-over-week shift',
    splitExperienceTitle: 'By experience',
    splitWorkplaceTitle: 'By workplace',
    moversTitle: 'Movers this week',
    moversGaining: 'Ramping up',
    moversCooling: 'Slowing down',
  },
  /**
   * Employer-audience strings. Kept in one block, mirroring the seeker sections
   * above, so shipped copy is reviewable in one place and i18n stays possible.
   *
   * Placeholders use {name}-style tokens filled at the call site — there is no
   * template engine here, and adding one for a handful of strings would be more
   * machinery than the problem needs.
   */
  employer: {
    nav: {
      dashboard: 'Dashboard',
      jobs: 'Jobs',
      assignments: 'Assignments',
      settings: 'Settings',
      hireSuffix: 'Hire',
    },
    jobs: {
      pageLabel: 'EMPLOYER',
      pageTitle: 'Postings',
      newPosting: 'New posting',
      editPosting: 'Edit posting',
      createPosting: 'Create posting',
      duplicatePosting: 'Duplicate',
      closeApplications: 'Close applications',
      positionFilled: 'Position filled',
      reopenPosting: 'Reopen',
      deletePosting: 'Delete',
      refresh: 'Refresh',
      statusActive: 'Active',
      statusDraft: 'Draft',
      statusClosed: 'Closed',
      applicants: 'applicants',
      noApplicants: 'No applicants yet',
      backToRanked: 'Back to Ranked',
      backToPipeline: 'Back to Pipeline',
      backToPosting: 'Back to posting',
      cancel: 'Cancel',
      save: 'Save',
      emptyTitle: 'No postings yet',
      emptyBody: 'Create your first job posting to start receiving applications.',
      emptyStatusTitle: 'No postings in this status',
      emptyStatusBody: 'Switch tabs above to see other postings.',
      loadError: 'Could not load postings.',
      viewApplicants: 'View applicants',
      tabAll: 'All',
    },
    applicants: {
      moveTo: 'Move to',
      archive: 'Archive',
      archiveConfirm: 'Archive {name}?',
      sendRejectionEmail: 'Send rejection email',
      scheduleInterview: 'Schedule interview',
      applyNow: 'Apply now',
      markApplied: 'Mark applied',
      addNote: 'Add a note',
      saveNote: 'Save Note',
      noNotes: 'No notes yet',
      rescore: 'Rescore',
      contact: 'Contact',
      skills: 'Skills',
      summary: 'Summary',
      timeline: 'Timeline',
      notes: 'Notes',
      score: 'Score',
      strong: 'strong',
      matched: 'Matched',
      bonus: 'Bonus',
      experience: 'Experience',
      location: 'Location',
      notice: 'Notice',
      alsoAppliedTo: 'Also applied to',
      alsoAppliedBanner: 'This candidate applied to {count} other {roleWord} at your company.',
      roleSingular: 'role',
      rolePlural: 'roles',
      rolesPill: '{count} roles',
      rolesPillLabel: 'Applied to {count} roles at your company',
      archivedBadge: 'Archived',
      exportData: 'Export candidate data',
      exportFailed: 'Could not export this candidate.',
      anonymize: 'Anonymize candidate',
      anonymizeTitle: 'Anonymize {name}?',
      anonymizeBody:
        "This permanently deletes {name}'s personal data, resume, and notes. Scores and pipeline history are kept for reporting. This cannot be undone.",
      anonymizeScope: 'This affects all {count} applications by this candidate.',
      anonymizeInterviewWarning:
        'This candidate has an interview scheduled for {date}. Anonymizing will NOT cancel it — cancel the interview first.',
      anonymizeConfirm: 'Anonymize',
      anonymizeDone: 'Candidate anonymized.',
      anonymizeAlready: 'This candidate was already anonymized.',
      anonymizeFailed: 'Could not anonymize this candidate.',
      anonymizeOwnerOnly: 'Only a Founder or Owner can anonymize a candidate.',
      feedbackTitle: 'Interview feedback',
      feedbackCount: '{completed}/{total} submitted',
      feedbackPending: 'Pending',
      feedbackViewFull: 'View full',
      feedbackCollapse: 'Show less',
      feedbackHeldTitle: 'Submit your feedback first',
      feedbackHeldBody:
        'You have an interview waiting on your feedback. Detailed responses from other interviewers unlock once you submit yours.',
      signalStrongHire: 'Strong hire',
      signalHire: 'Hire',
      signalMixed: 'Mixed',
      signalNoHire: 'No hire',
      recStrongYes: 'Strong yes',
      recYes: 'Yes',
      recNo: 'No',
      recStrongNo: 'Strong no',
      doNotContact: 'Do not contact',
      doNotContactSet: 'Mark do not contact',
      doNotContactClear: 'Remove do not contact',
      doNotContactBanner: 'Do not contact',
      doNotContactMeta: 'Set by {name} on {date}',
      doNotContactUnknownSetter: 'a teammate',
      doNotContactDialogTitle: 'Mark {name} as do not contact?',
      doNotContactDialogBody:
        'They stay in the pipeline, but everyone at your company sees a warning before reaching out. This applies to every posting they appear on.',
      doNotContactClearTitle: 'Remove the do not contact flag?',
      doNotContactClearBody: 'The warning disappears and the recorded reason is cleared.',
      doNotContactReasonLabel: 'Reason (optional)',
      doNotContactReasonPlaceholder: 'Asked us not to contact them again',
      doNotContactSaved: 'Marked do not contact.',
      doNotContactCleared: 'Do not contact removed.',
      doNotContactFailed: 'Could not update that flag.',
      doNotContactMemberOnly: 'Only Members and above can change this.',
      doNotContactRowLabel: 'Do not contact',
    },
    dpdp: {
      queueTitle: 'Erasure requests',
      queueSubtitle: 'Open DPDP rights requests awaiting fulfilment.',
      queueEmpty: 'No open erasure requests',
      queueEmptyBody: 'Requests appear here as candidates file them.',
      process: 'Process',
      processAll: 'Process all pending',
      processing: 'Processing…',
      processed: 'Request fulfilled.',
      processFailed: 'Could not fulfil this request.',
      columnEmail: 'Email',
      columnType: 'Type',
      columnSubmitted: 'Submitted',
      columnDue: 'Due by',
      columnAction: '',
      overdue: 'Overdue',
      loadError: 'Could not load rights requests.',
      requestMyData: 'Request my data',
      requestMyDataBody:
        'We’ll email you a one-time link to download the data this company holds about you. The link expires in 24 hours.',
      requestMyDataAction: 'Email me a download link',
      requestMyDataSent:
        'If we hold data for that email, we’ve sent a download link to it. The link expires in 24 hours.',
      requestMyDataFailed: 'Could not submit that request. Try again.',
      emailLabel: 'Your email address',
    },
    settings: {
      title: 'Settings',
      company: 'Company',
      companySubtitle: 'Your company profile and public careers page.',
      team: 'Team',
      roles: 'Roles',
      rolesTitle: 'Roles & permissions',
      rolesSubtitle: 'Role permissions are fixed in the current version. Custom roles are coming soon.',
      email: 'Email',
      branding: 'Branding',
      brandingSubtitle: 'How your company appears to candidates.',
      personal: 'Personal',
      personalSubtitle: 'Your photo, timezone, and what we email you about.',
      assignments: 'Assignments',
      dangerZone: 'Danger zone',
    },
    assignments: {
      pageTitle: 'Assignments',
      pageSubtitle: 'Reusable take-home tasks you can attach to any posting.',
      newAssignment: 'New assignment',
      showArchived: 'Show archived',
      emptyTitle: 'No assignments yet',
      emptyBody: 'Create a reusable take-home task you can attach to any posting.',
      emptyAction: 'Create your first assignment',
      columnTitle: 'Title',
      columnHours: 'Est. hours',
      columnAccepts: 'Accepts',
      columnUsedBy: 'Used by',
      columnStatus: 'Status',
      columnActions: 'Actions',
      linkOnly: 'Link only',
      statusActive: 'Active',
      statusArchived: 'Archived',
      untitledPosting: 'Untitled posting',
      view: 'View',
      edit: 'Edit',
      clone: 'Clone',
      archive: 'Archive',
      unarchive: 'Unarchive',
      roleReasonEdit: 'Only Members and above can edit assignments.',
      roleReasonClone: 'Only Members and above can clone assignments.',
      roleReasonArchive: 'Only Owners can archive assignments.',
      unarchiveBeforeEdit: 'Unarchive this assignment before editing it.',
    },
    personal: {
      photo: 'Profile photo',
      photoHint: 'PNG, JPG, or WebP. Max 2 MB. Square works best.',
      upload: 'Upload photo',
      replace: 'Replace photo',
      remove: 'Remove photo',
      photoUpdated: 'Photo updated.',
      photoRemoved: 'Photo removed.',
      photoTooLarge: 'That file is {size}. The limit is 2 MB.',
      photoFailed: 'Could not upload that photo. Check your connection and try again.',
      identity: 'Name and email',
      identityHint: 'These come from your Google account and cannot be changed here.',
      nameLabel: 'Display name',
      emailLabel: 'Email',
      jobTitleLabel: 'Job title',
      jobTitleHint: 'Shown next to your name on notes and interview invitations.',
      jobTitlePlaceholder: 'Talent Partner',
      timezoneLabel: 'Timezone',
      timezoneHint: 'Dates and times across JobMesh are shown in this zone.',
      currentTime: 'Current time: {time}',
      saveFailed: 'Could not save your settings.',
      saved: 'Settings saved.',
      notifications: 'Email notifications',
      notificationsHint: 'Everything is on until you turn it off. Changes save as you make them.',
      notificationsSaved: 'Saved.',
      notificationsFailed: 'Could not save that preference.',
      groupApplications: 'Applications',
      groupInterviews: 'Interviews',
      groupCollaboration: 'Collaboration',
      groupDeadlines: 'Deadlines',
      eventNewApplication: 'New application',
      eventNewApplicationHint: 'Someone applies to a posting at your company.',
      eventStageChange: 'Stage change',
      eventStageChangeHint: 'A candidate moves to a different stage.',
      eventCandidateHired: 'Candidate hired',
      eventCandidateHiredHint: 'A candidate is moved into a hired stage.',
      eventInterviewScheduled: 'Interview scheduled',
      eventInterviewScheduledHint: 'An interview is booked on one of your postings.',
      eventInterviewReminder: 'Interview reminder',
      eventInterviewReminderHint: 'A reminder before an interview you are on.',
      eventFeedbackSubmitted: 'Feedback submitted',
      eventFeedbackSubmittedHint: 'A teammate submits their interview feedback.',
      eventNoteMention: 'Mentions',
      eventNoteMentionHint: 'A teammate @mentions you in a note.',
      eventApplicationDeadline: 'Deadline approaching',
      eventApplicationDeadlineHint: 'A posting you own is about to close.',
    },
    onboarding: {
      title: 'Set up your company',
      subtitle: 'Tell us about your company to get started.',
    },
    login: {
      title: 'Employer login',
      subtitle: 'Sign in to manage your hiring.',
    },
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welcome back',
    },
    common: {
      edit: 'Edit',
      view: 'View',
      clone: 'Clone',
      delete: 'Delete',
      confirm: 'Confirm',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving…',
      saved: 'Saved',
      loading: 'Loading…',
      actions: 'Actions',
      showArchived: 'Show archived',
      retry: 'Retry',
    },
  },
} as const;

export { BRAND, BRAND_SPLIT, SKETCH_FONT, PALETTE, COPY };

export default { BRAND, BRAND_SPLIT, SKETCH_FONT, PALETTE, COPY };
