// FILE: src/theme/copy-seeker.ts
// Every string the SEEKER and public surfaces render: nav, home, jobs, progress,
// directory, footer, legal, site metadata and trends. Split out of brand.ts
// (naming conventions section 2).
//
// Split by AUDIENCE rather than arbitrarily, because that is the boundary the rest
// of the codebase already draws (section 0): a seeker page never needs an employer
// string, and keeping them apart makes that visible.

import { SEEKER_HOME_COPY } from './copy-seeker-home';

export const SEEKER_COPY = {
  nav: {
    today: 'Today',
    companies: 'Companies',
    browseJobs: 'Jobs',
    myProgress: 'Progress',
    hiring: 'Hiring',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
  },
  jobs: {
    pageLabel: 'Opportunities',
    pageTitle: 'All tech jobs',
    rolesAvailable: 'roles available',
    noJobsTitle: 'No jobs found',
    noJobsBody: 'Try a different company or view all roles.',
    noEntryJobsBody: 'No entry-level roles found. Try turning off the fresher filter.',
    clearFilters: 'Clear filters',
    allJobs: 'All jobs',
    allCompanies: 'All companies',
    experienceLabel: 'Experience',
    companiesLabel: 'Companies',
    entryLevel: 'Entry level / Fresher',
    allLevels: 'All experience levels',
    applyNow: 'Apply now',
    readMore: 'Read more',
    showLess: 'Show less',
    postedPrefix: 'Posted',
    postedNA: 'No date',
    feedTitle: 'Job feed',
    rolesLabel: 'roles',
    filterLabel: 'Filter',
  },
  progress: {
    pageLabel: 'Tracking',
    pageTitle: 'My progress',
    backToJobs: 'Back to jobs',
    todayLabel: 'Today',
    noStreak: 'No streak yet',
    historyLabel: 'Recent applications',
    historySubtitle: 'Your latest applied jobs, useful for follow-ups and interview prep.',
    emptyTitle: 'No applications tracked yet',
    emptyBody: 'Start applying from the jobs feed and your recent history will appear here.',
  },
  directory: {
    pageLabel: 'Company directory',
    pageTitle1: 'Tech companies',
    pageTitle2: 'hiring in India',
    subtitle: 'Companies actively hiring across India — updated daily.',
    searchPlaceholder: 'Search companies…',
    searchAriaLabel: 'Search companies',
    sortAriaLabel: 'Sort companies',
    noCompaniesTitle: 'No companies found',
    noCompaniesBody: 'Try a different search term or clear your filters.',
    sortAZ: 'A → Z',
    sortZA: 'Z → A',
    sortMostHiring: 'Most hiring',
    documentTitle: 'Tech companies hiring in India · JobMesh',
  },
  footer: {
    navigateTitle: 'Navigate',
    jobFeedLink: 'Job feed',
    companiesLink: 'Companies',
    legalTitle: 'Legal',
    legalInfoLink: 'Legal info',
    privacyLink: 'Privacy',
    contactLink: 'Contact',
    disclaimer: 'A non-commercial aggregator. Job details are collected automatically — verify directly with employers.',
  },
  legal: {
    pageLabel: 'Legal',
    pageTitle: 'Legal information',
    lastUpdated: 'Last updated: March 2026',
    contactTitle: 'Contact',
    contactBody: 'For questions, data deletion requests, or legal enquiries, reach out at layer3studios.team@gmail.com.',
    sections: [],
  },
  site: {
    documentTitleJobs: 'Browse tech jobs in India · JobMesh',
    documentTitleProgress: 'My progress · JobMesh',
  },
  trends: {
    pageLabel: 'Market signal',
    pageTitle: 'Hiring trends in',
    pageTitleAccent: 'India',
    subtitle: 'How tech hiring is moving — posting momentum, role demand, and who is ramping up.',
    shareButtonLabel: 'Share',
    shareTitle: 'Hiring trends in India · JobMesh',
    documentTitle: 'Hiring trends in India · JobMesh',
    errorTitle: "Couldn't load trends",
    errorBody: 'Something went wrong. Try refreshing.',
    emptyTitle: 'Not enough data yet',
    emptyBody: 'Trend signals will appear here as more roles come in.',
    updatedPrefix: 'Updated',
    summaryTotalRoles: 'Open roles',
    summaryNewThisWeek: 'New this week',
    summaryMomentum: 'Week over week',
    summaryCompanies: 'Companies tracked',
    momentumTitle: 'Posting momentum',
    momentumSub: 'New roles added per day over the last 60 days',
    categoriesTitle: 'Role demand',
    categoriesSub: 'Share of open roles by category, with week-over-week shift',
    splitExperienceTitle: 'By experience',
    splitWorkplaceTitle: 'By workplace',
    moversTitle: 'Movers this week',
    moversGaining: 'Ramping up',
    moversCooling: 'Slowing down',
  },
  ...SEEKER_HOME_COPY,
} as const;
