// FILE: src/theme/copy-employer-jobs.ts
// Postings and applicants -- the two surfaces an employer lives in. Split out of
// copy-employer.ts (section 2).

export const EMPLOYER_JOBS_COPY = {
  jobs: {
    pageLabel: 'EMPLOYER',
    pageTitle: 'Postings',
    newPosting: 'New posting',
    editPosting: 'Edit posting',
    createPosting: 'Create posting',
    duplicatePosting: 'Duplicate',
    closeApplications: 'Close applications',
    positionFilled: 'Position filled',
    reopenPosting: 'Reopen',
    deletePosting: 'Delete',
    refresh: 'Refresh',
    statusActive: 'Active',
    statusDraft: 'Draft',
    statusClosed: 'Closed',
    applicants: 'applicants',
    noApplicants: 'No applicants yet',
    backToRanked: 'Back to Ranked',
    backToPipeline: 'Back to Pipeline',
    backToPosting: 'Back to posting',
    cancel: 'Cancel',
    save: 'Save',
    emptyTitle: 'No postings yet',
    emptyBody: 'Create your first job posting to start receiving applications.',
    emptyStatusTitle: 'No postings in this status',
    emptyStatusBody: 'Switch tabs above to see other postings.',
    loadError: 'Could not load postings.',
    viewApplicants: 'View applicants',
    tabAll: 'All',
  },
  applicants: {
    moveTo: 'Move to',
    archive: 'Archive',
    archiveConfirm: 'Archive {name}?',
    sendRejectionEmail: 'Send rejection email',
    scheduleInterview: 'Schedule interview',
    applyNow: 'Apply now',
    markApplied: 'Mark applied',
    addNote: 'Add a note',
    saveNote: 'Save Note',
    noNotes: 'No notes yet',
    rescore: 'Rescore',
    contact: 'Contact',
    skills: 'Skills',
    summary: 'Summary',
    timeline: 'Timeline',
    notes: 'Notes',
    score: 'Score',
    strong: 'strong',
    matched: 'Matched',
    bonus: 'Bonus',
    experience: 'Experience',
    location: 'Location',
    notice: 'Notice',
    alsoAppliedTo: 'Also applied to',
    alsoAppliedBanner: 'This candidate applied to {count} other {roleWord} at your company.',
    roleSingular: 'role',
    rolePlural: 'roles',
    rolesPill: '{count} roles',
    rolesPillLabel: 'Applied to {count} roles at your company',
    archivedBadge: 'Archived',
    exportData: 'Export candidate data',
    exportFailed: 'Could not export this candidate.',
    anonymize: 'Anonymize candidate',
    anonymizeTitle: 'Anonymize {name}?',
    anonymizeBody:
      "This permanently deletes {name}'s personal data, resume, and notes. Scores and pipeline history are kept for reporting. This cannot be undone.",
    anonymizeScope: 'This affects all {count} applications by this candidate.',
    anonymizeInterviewWarning:
      'This candidate has an interview scheduled for {date}. Anonymizing will NOT cancel it — cancel the interview first.',
    anonymizeConfirm: 'Anonymize',
    anonymizeDone: 'Candidate anonymized.',
    anonymizeAlready: 'This candidate was already anonymized.',
    anonymizeFailed: 'Could not anonymize this candidate.',
    anonymizeOwnerOnly: 'Only a Founder or Owner can anonymize a candidate.',
    feedbackTitle: 'Interview feedback',
    feedbackCount: '{completed}/{total} submitted',
    feedbackPending: 'Pending',
    feedbackViewFull: 'View full',
    feedbackCollapse: 'Show less',
    feedbackHeldTitle: 'Submit your feedback first',
    feedbackHeldBody:
      'You have an interview waiting on your feedback. Detailed responses from other interviewers unlock once you submit yours.',
    signalStrongHire: 'Strong hire',
    signalHire: 'Hire',
    signalMixed: 'Mixed',
    signalNoHire: 'No hire',
    recStrongYes: 'Strong yes',
    recYes: 'Yes',
    recNo: 'No',
    recStrongNo: 'Strong no',
    doNotContact: 'Do not contact',
    doNotContactSet: 'Mark do not contact',
    doNotContactClear: 'Remove do not contact',
    doNotContactBanner: 'Do not contact',
    doNotContactMeta: 'Set by {name} on {date}',
    doNotContactUnknownSetter: 'a teammate',
    doNotContactDialogTitle: 'Mark {name} as do not contact?',
    doNotContactDialogBody:
      'They stay in the pipeline, but everyone at your company sees a warning before reaching out. This applies to every posting they appear on.',
    doNotContactClearTitle: 'Remove the do not contact flag?',
    doNotContactClearBody: 'The warning disappears and the recorded reason is cleared.',
    doNotContactReasonLabel: 'Reason (optional)',
    doNotContactReasonPlaceholder: 'Asked us not to contact them again',
    doNotContactSaved: 'Marked do not contact.',
    doNotContactCleared: 'Do not contact removed.',
    doNotContactFailed: 'Could not update that flag.',
    doNotContactMemberOnly: 'Only Members and above can change this.',
    doNotContactRowLabel: 'Do not contact',
  },
} as const;
