// FILE: src/theme/copy-employer-hiring.ts
// The hiring add-ons: referrals, screening questions, careers-page culture and
// interview availability. Split out of copy-employer.ts (section 2).

export const EMPLOYER_HIRING_COPY = {
  // Employee referrals. Written for the teammate doing the sharing, not for the
  // system doing the tracking: "your link", not "referral link entity".
  referrals: {
    sectionTitle: 'Refer someone',
    sectionBody: 'Share this role with your network. Anyone who applies through your link is credited to you.',
    copyLink: 'Copy your link',
    copying: 'Preparing link…',
    copied: 'Referral link copied. Share it with your network.',
    copyFailed: 'Could not copy the link. Try again.',
    loadFailed: 'Could not load referral activity.',
    statsEmpty: 'No clicks yet.',
    // "{clicks} clicks · {applications} applications from your link"
    stats: '{clicks} clicks · {applications} applications from your link',
    activityTitle: 'Referral activity',
    activityEmpty: 'Nobody has shared this role yet.',
    activityColumnPerson: 'Teammate',
    activityColumnClicks: 'Clicks',
    activityColumnApplications: 'Applications',
    deactivate: 'Deactivate',
    deactivated: 'Inactive',
    deactivateFailed: 'Could not deactivate that link.',
    referredByLabel: 'Referred by {name}',
    rowBadge: 'Referral',
    rowBadgeTooltip: 'Referred by {name}',
  },
  // Screening questions. "Flag", never "knockout" or "reject" — the feature
  // marks an answer for a human to read, and calling it a knockout would invite
  // employers to trust it as an automatic rejection, which it is not.
  screening: {
    sectionTitle: 'Screening questions',
    sectionBody: 'Ask up to 5 questions on the apply form. Answers appear on the candidate’s profile.',
    addQuestion: 'Add question',
    limitReached: 'You can ask up to 5 questions.',
    questionLabel: 'Question',
    questionPlaceholder: 'e.g. Do you have a valid work permit?',
    typeLabel: 'Answer type',
    typeText: 'Short text',
    typeSelect: 'Multiple choice',
    typeYesNo: 'Yes / No',
    optionsLabel: 'Choices',
    addOption: 'Add choice',
    removeOption: 'Remove choice',
    requiredLabel: 'Required',
    flagToggle: 'Flag one answer for review',
    flagSelectLabel: 'Flag candidates who answer:',
    flagHint: 'Flagged answers are highlighted on the candidate’s profile. Nobody is rejected automatically.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove question',
    collapsedUntitled: 'Untitled question',
    // Candidate-facing
    applyLegend: 'A few questions',
    // Employer review surfaces
    answersTitle: 'Screening answers',
    flaggedAnswerTooltip: 'This answer was flagged by the employer.',
    flaggedBanner: '{count} flagged answer',
    flaggedBannerPlural: '{count} flagged answers',
    rowFlagLabel: 'Has a flagged screening answer',
  },
  // Careers-page culture section. Addressed to the employer filling it in, and
  // written about what candidates will see rather than about the data model.
  culture: {
    sectionTitle: 'Culture',
    sectionBody: 'Shown on your careers page, above your open roles.',
    headlineLabel: 'Headline',
    headlinePlaceholder: 'Why work at your company?',
    descriptionLabel: 'About working here',
    descriptionPlaceholder: 'What is the team like? How do you work? What do you care about?',
    benefitsLabel: 'Benefits',
    benefitsHint: 'Up to 8. A title is enough — the icon and description are optional.',
    addBenefit: 'Add benefit',
    benefitLimit: 'You can add up to 8 benefits.',
    benefitIconLabel: 'Icon',
    benefitTitleLabel: 'Benefit',
    benefitTitlePlaceholder: 'Health insurance',
    benefitDescriptionLabel: 'Description',
    benefitDescriptionPlaceholder: 'Family cover from day one.',
    removeBenefit: 'Remove benefit',
    moveBenefitUp: 'Move benefit up',
    moveBenefitDown: 'Move benefit down',
    photosLabel: 'Photos',
    photosHint: 'Up to 4. PNG, JPG or WebP, max 5 MB each.',
    addPhoto: 'Add photo',
    removePhoto: 'Remove photo',
    photoLimit: 'You can add up to 4 photos.',
    photoTooLarge: 'That photo is {size}. The limit is 5 MB.',
    photoUploadFailed: 'Could not upload that photo.',
    save: 'Save culture section',
    saving: 'Saving…',
    saved: 'Careers page updated.',
    saveFailed: 'Could not save. Try again.',
    previewLink: 'View your careers page',
  },
  // Weekly interview availability. Written as the person's own statement about
  // their week — "when you can interview", not "availability records".
  availability: {
    sectionTitle: 'Interview availability',
    sectionBody: 'The hours you can take interviews. Used to suggest times when scheduling.',
    timezoneNote: 'Times shown in {timezone}',
    timezoneMissing: 'Set your timezone above so these hours land where you expect.',
    presetsLabel: 'Quick set',
    presetBusiness: 'Business hours',
    presetExtended: 'Extended',
    presetClear: 'Clear all',
    startLabel: 'From',
    endLabel: 'To',
    unavailable: 'Not available',
    saved: 'Availability saved.',
    saveFailed: 'Could not save your availability.',
    loadFailed: 'Could not load your availability.',
    // Suggestion surface
    suggestTitle: 'Suggest from availability',
    suggestBody: 'Times drawn from your weekly hours, minus anything already booked.',
    suggestButton: 'Suggest times',
    suggestLoading: 'Finding times…',
    suggestEmpty: 'No free times in your hours for this range.',
    suggestNoHours: 'Set your interview hours in personal settings first.',
    suggestSkipped: '{count} skipped — already booked',
    suggestSelectAll: 'Select all',
    suggestClear: 'Clear selection',
    suggestAdd: 'Add {count} times',
    suggestFailed: 'Could not load suggestions.',
  },
} as const;
