// FILE: src/theme/copy-employer-shell.ts
// Navigation, settings, assignments library, personal settings, onboarding, login,
// dashboard and shared labels. Split out of copy-employer.ts (section 2).

export const EMPLOYER_SHELL_COPY = {
  nav: {
    dashboard: 'Dashboard',
    jobs: 'Jobs',
    assignments: 'Assignments',
    settings: 'Settings',
    hireSuffix: 'Hire',
  },
  dpdp: {
    queueTitle: 'Erasure requests',
    queueSubtitle: 'Open DPDP rights requests awaiting fulfilment.',
    queueEmpty: 'No open erasure requests',
    queueEmptyBody: 'Requests appear here as candidates file them.',
    process: 'Process',
    processAll: 'Process all pending',
    processing: 'Processing…',
    processed: 'Request fulfilled.',
    processFailed: 'Could not fulfil this request.',
    columnEmail: 'Email',
    columnType: 'Type',
    columnSubmitted: 'Submitted',
    columnDue: 'Due by',
    columnAction: '',
    overdue: 'Overdue',
    loadError: 'Could not load rights requests.',
    requestMyData: 'Request my data',
    requestMyDataBody:
      'We’ll email you a one-time link to download the data this company holds about you. The link expires in 24 hours.',
    requestMyDataAction: 'Email me a download link',
    requestMyDataSent:
      'If we hold data for that email, we’ve sent a download link to it. The link expires in 24 hours.',
    requestMyDataFailed: 'Could not submit that request. Try again.',
    emailLabel: 'Your email address',
  },
  settings: {
    title: 'Settings',
    company: 'Company',
    companySubtitle: 'Your company profile and public careers page.',
    team: 'Team',
    roles: 'Roles',
    rolesTitle: 'Roles & permissions',
    rolesSubtitle: 'Role permissions are fixed in the current version. Custom roles are coming soon.',
    email: 'Email',
    branding: 'Branding',
    brandingSubtitle: 'How your company appears to candidates.',
    personal: 'Personal',
    personalSubtitle: 'Your photo, timezone, and what we email you about.',
    assignments: 'Assignments',
    dangerZone: 'Danger zone',
  },
  assignments: {
    pageTitle: 'Assignments',
    pageSubtitle: 'Reusable take-home tasks you can attach to any posting.',
    newAssignment: 'New assignment',
    showArchived: 'Show archived',
    emptyTitle: 'No assignments yet',
    emptyBody: 'Create a reusable take-home task you can attach to any posting.',
    emptyAction: 'Create your first assignment',
    columnTitle: 'Title',
    columnHours: 'Est. hours',
    columnAccepts: 'Accepts',
    columnUsedBy: 'Used by',
    columnStatus: 'Status',
    columnActions: 'Actions',
    linkOnly: 'Link only',
    statusActive: 'Active',
    statusArchived: 'Archived',
    untitledPosting: 'Untitled posting',
    view: 'View',
    edit: 'Edit',
    clone: 'Clone',
    archive: 'Archive',
    unarchive: 'Unarchive',
    roleReasonEdit: 'Only Members and above can edit assignments.',
    roleReasonClone: 'Only Members and above can clone assignments.',
    roleReasonArchive: 'Only Owners can archive assignments.',
    unarchiveBeforeEdit: 'Unarchive this assignment before editing it.',
  },
  personal: {
    photo: 'Profile photo',
    photoHint: 'PNG, JPG, or WebP. Max 2 MB. Square works best.',
    upload: 'Upload photo',
    replace: 'Replace photo',
    remove: 'Remove photo',
    photoUpdated: 'Photo updated.',
    photoRemoved: 'Photo removed.',
    photoTooLarge: 'That file is {size}. The limit is 2 MB.',
    photoFailed: 'Could not upload that photo. Check your connection and try again.',
    identity: 'Name and email',
    identityHint: 'These come from your Google account and cannot be changed here.',
    nameLabel: 'Display name',
    emailLabel: 'Email',
    jobTitleLabel: 'Job title',
    jobTitleHint: 'Shown next to your name on notes and interview invitations.',
    jobTitlePlaceholder: 'Talent Partner',
    timezoneLabel: 'Timezone',
    timezoneHint: 'Dates and times across JobMesh are shown in this zone.',
    currentTime: 'Current time: {time}',
    saveFailed: 'Could not save your settings.',
    saved: 'Settings saved.',
    notifications: 'Email notifications',
    notificationsHint: 'Everything is on until you turn it off. Changes save as you make them.',
    notificationsSaved: 'Saved.',
    notificationsFailed: 'Could not save that preference.',
    groupApplications: 'Applications',
    groupInterviews: 'Interviews',
    groupCollaboration: 'Collaboration',
    groupDeadlines: 'Deadlines',
    eventNewApplication: 'New application',
    eventNewApplicationHint: 'Someone applies to a posting at your company.',
    eventStageChange: 'Stage change',
    eventStageChangeHint: 'A candidate moves to a different stage.',
    eventCandidateHired: 'Candidate hired',
    eventCandidateHiredHint: 'A candidate is moved into a hired stage.',
    eventInterviewScheduled: 'Interview scheduled',
    eventInterviewScheduledHint: 'An interview is booked on one of your postings.',
    eventInterviewReminder: 'Interview reminder',
    eventInterviewReminderHint: 'A reminder before an interview you are on.',
    eventFeedbackSubmitted: 'Feedback submitted',
    eventFeedbackSubmittedHint: 'A teammate submits their interview feedback.',
    eventNoteMention: 'Mentions',
    eventNoteMentionHint: 'A teammate @mentions you in a note.',
    eventApplicationDeadline: 'Deadline approaching',
    eventApplicationDeadlineHint: 'A posting you own is about to close.',
  },
  onboarding: {
    title: 'Set up your company',
    subtitle: 'Tell us about your company to get started.',
  },
  login: {
    title: 'Employer login',
    subtitle: 'Sign in to manage your hiring.',
  },
  dashboard: {
    title: 'Dashboard',
    welcome: 'Welcome back',
  },
  common: {
    edit: 'Edit',
    view: 'View',
    clone: 'Clone',
    delete: 'Delete',
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    loading: 'Loading…',
    actions: 'Actions',
    showArchived: 'Show archived',
    retry: 'Retry',
  },
} as const;
